### ISSUE TITLE
generated/ is empty (when installing from npm)

### ISSUE THREAD

**Issue by mvayngrib** [cheminfo-js/mrz#3]

**Comment by mvayngrib** [comment]
i guess "main" in package.json should point to ./dist/mrz.min.js

**Comment by jsanta** [comment]
Just faced the same problem. Made a merge using another another mrz utility.
https://gist.github.com/jsanta/434c2d49e2ad5ec10395a61b864c7da5

**Comment by lpatiny** [comment]
closed by 08e1992079a625260db5fc1505ad99dcc28f0793

After npm install this returns now the correct result

` mrz.parse('I<UTOD231458907<<<<<<<<<<<<<<<\r\n7408122F1204159FRA<<<<<<<<<<<6\r\nERIKSSON<<ANNA<MARIA<<<<<<<<<<')
`
