### ISSUE TITLE
Help with picture processing before extracting MRZ

### ISSUE THREAD

**Issue by opmiguel** [cheminfo-js/mrz#4]
Hi Guys,

I went over the resources you published and I was able to find a lot of solutions for some of the issues we are having with MRZ extraction.
I am contacting you to see if maybe you have find some good solutions for pre-processing an ID picture before the MRZ can be read. I have found that many users struggle to take a good enough picture of their IDs.
I am looking for somebody to help us setup a demo for a project.

In a Nutshell, We are setting up a demo for a project to ensure that only people above a certain age can register to an event and purchase tickets (for example: to a concert, to a festival etc.).
Our idea is to ask the user during the registration process to upload its ID containing an MRZ and that we check if the person is over 16, 18 etc.

Our requirements:
	• The picture of the ID needs to be processed by our system and cannot be sent to an external system for security reasons (for example: not to https://www.ocrsdk.com).
	• Our biggest constraint is that we cannot use a mobile APP (no Android APP, no IOS APP). At the moment our environment is spring with NGINX (Angular6, material design)
	• The solution needs to work as a step in a normal registration website.
	• We need to guarantee that the date of birth used for the check:
		○ It is ok to stop the registration because the quality is not good enough
		○ However it would be an automatic failure for our project if the extracted date of birth is wrong and we allow a 14 years old to register an over 18 event. 

Our issues so far:
	• There are plenty of solutions that work great with mobile APPs (ios, android). These solutions allow detecting that an image resolution is decent, that it is not blurry etc. However, we cannot ask a user to install an app for our project and are stuck with the Web approach.
	• I am struggling to pre-process the picture so that it can be decent enough for the OCR (un-skew, rotate, resize)

Our demo would be:
	1. User goes to our public website (does not exist yet)
	2. User is requested to take or upload  a picture in its web browser
		a. ALT: If possible, he gets an hint if the picture is decent enough straight away (not to skewed, not to blurry, not too close, not too far etc.). He is asked to retry if the picture quality if not sufficient
	3. The MRZ is processed (locally if possible or by our server).
	4. The MRZ data is sent to our backend
	5. The fields are pre-populated with the extracted information .
	6. The front end blocks the registration if the user does not meet the minimum age requirement.

In a nutshell, we are looking for somebody who could help us with the part of consistent image processing and extraction of the MRZ. I was hoping that you could give us some pointers or even help us build this element of the demo for a fee. Alternatively if you could recommend us to somebody else that would be also great.

Cheers,

Miguel

**Comment by stropitek** [comment]
Hello @opmiguel 

We would gladly collaborate if it can improve our libraries.

Can you contact me by email, so that I can respond privately?
