### ISSUE TITLE
Support es5

### ISSUE THREAD

**Issue by tuqire** [cheminfo-js/mrz#5]
Hi,

Is there any plans to support es5 syntax? Right now Webpack Uglify throws an error as const is being used.

I am happy to put in a pr if you're happy with it.

**Comment by targos** [comment]
There are no plans to support older syntax in this package. It is possible to transpile the code with babel before passing it through uglify or use [terser](https://github.com/webpack-contrib/terser-webpack-plugin) instead of uglify
