### ISSUE TITLE
Cannot parse passport name fields with spaces in them

### ISSUE THREAD

**Issue by aeisenberg** [cheminfo-js/mrz#7]
My passport has the following MRZ text on it:

```
P<CANEISENBERG<CANDREW DAVID<<<<<<<<<<<<<<<<
AC773749<3CAN7612220M2710257<<<<<<<<<<<<<<00
```
Notice the space between `ANDREW` and `DAVID`. The regex you are using to parse the name field looks like this:

```/^[A-Z<]+<*$/```

It does not accept spaces and therefore fails to parse the MRZ of the passport above. Things seem to work if I add a space to the regex, like so:

```/^[A-Z< ]+<*$/```

Want me to make a PR?

**Comment by aeisenberg** [comment]
On a deeper look, it's a bit more complicated. The MRZ above has an OCR error. The text reads `<CANDREW`. it should be `<<ANDREW`. That's contributing to the problem, though even if I replace the `C` with a `<`, I still get an error reading the first name. The last name is picked up fine, though _if_ there were a space in my last name, there would be an error, too.

**Comment by aeisenberg** [comment]
On a deeper look, this appears to be an OCR issue. There should not be any space between `ANDREW` and `DAVID`. It should be `<`. And the `C` before `ANDREW` is actually a `<`. 

If I manually make those changes, then the package works perfectly!

Apologies for the noise.

**Comment by targos** [comment]
No problem. Happy that you found what was the issue.
